<?php
/**
 * IRKit Wrapper
 * IRKit Wrapper
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\RESTfulAPI\Codegen;

class Routes
{
    public static function addWebRoutes()
    {
        // web routes are not supported yet.
    }

    public static function addApiRoutes()
    {
        // IRKit Wrapper (1.0.0)
        \Route::GET('/api/command/{accessory}/{command}', '\App\RESTfulAPI\Controllers\IrkitApi@commandWithValidate');
    }
}
