<?php
/**
 * IRKit Wrapper
 * IRKit Wrapper
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\RESTfulAPI\Controllers;

use App;
use App\RESTfulAPI\Codegen\Controllers\IrkitApiBase;
use Crhg\IRKit\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class IrkitApi extends IrkitApiBase
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation command
     *
     * issue a command to accessory.
     *
     * @param Request $request http request
     * @param string $accessory accessory name (required)
     * @param string $command command name (required)
     *
     * @return \Illuminate\Http\Response
     */
    protected function command(Request $request, $accessory, $command)
    {
        $config = config('irkit_client');
        $config['logger'] = Log::getMonolog();

        /** @var Client $irkit_client */
        $irkit_client = App::makeWith(Client::class, ['config_array' => $config]);

        $irkit_client->send($accessory, $command);
        return response('OK');
    }

}
