<?php
/**
 * IRKit Wrapper
 * IRKit Wrapper
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\RESTfulAPI\Controllers;

use App;
use App\RESTfulAPI\Codegen\Controllers\IrkitApiBase;
use Crhg\LaravelIRKit\Facades\IRKit;

class IrkitApi extends IrkitApiBase
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation command
     *
     * issue a command to accessory.
     *
     * @param string $accessory accessory name (required)
     * @param string $command command name (required)
     *
     * @return \Illuminate\Http\Response
     */
    protected function command($accessory, $command)
    {
        IRKit::send($accessory, $command);
        return response('OK');
    }

}
